### ISSUE TITLE
Error when adding integration

### ISSUE THREAD

**Issue by gsolem** [jaroschek/home-assistant-myuplink#1]
Trying to add this integration to HA after downloading via HACS. I just get the following error after inputting the cliend ID and secret when added to HA integration: 

![image](https://user-images.githubusercontent.com/15731163/196008362-058a54ee-8027-4a85-abc7-434ea3967947.png)

**Comment by jaroschek** [comment]
Hi, I'm sorry you have a problem with the integration. I will have a look into it.

I know, that the documentation is still missing in this repository. So please ensure to provide the correct callback url, when you create/edit your application in https://dev.myuplink.com

You should typically use the following in a standard installation of Home Assistant:

https://my.home-assistant.io/redirect/oauth

I my case the configured application looks like this:
<img width="880" alt="image" src="https://user-images.githubusercontent.com/470290/196027589-983c9b75-853b-44a3-a4f1-d1f94c4d5daa.png">

And please use the disk-button to copy the client secret to your clipboard, when you copy&paste it into the configuration popup in Home Assistant.

If this is not helpful, can you provide the address the is causing the error? It should not contain your client secret. But it could give a hint, why it causes this error.

**Comment by gsolem** [comment]
Hi, I tried now with different callback url's but it always fail. 

First I tried with https://my.ha-address.com:portnumber/redirect/oauth but same failure.
Then https://my.ha-address.com/redirect/oauth and it also fails.

Are you sure /redirect/oauth is correct behind the HA address/URL?

**Comment by gsolem** [comment]
Just checking if anyone has had a chance testing this recently, without getting the same error when adding the integration?

**Comment by mgregersen** [comment]
@gsolem I figured it out 😄  It is not possible to update the Callback URL on the existing app in dev.myuplink.com, because it's not being saved... So I just created a new app and set the URL to "https://my.home-assistant.io/redirect/oauth" from the start, and then it is saved correctly on the app. In Home Assistant you have to remove the saved Application Credentials and start from scratch with the new app keys 👍

**Comment by gsolem** [comment]
@mgregersen Thanks, but I tried this earlier without success. Just tried it again but same error. It's almost like it doesn't even try, as the error shows instantly.

**Comment by mgregersen** [comment]
@gsolem I experienced something similar, but after I deleted the application credentials in Home Assistant (https://www.home-assistant.io/integrations/application_credentials/), I could set up the integration from scratch with the new app keys from myUplink, where the Callback URL then matches the request from Home Assistant, and then it worked 😊

**Comment by gsolem** [comment]
Thanks @mgregersen, finally I could get it to work! Stupid mistake, I used my own HA URL as the callback URL...

But I only get the sensors (45 of them), the climate device was not created. Not sure why.

**Comment by mgregersen** [comment]
@gsolem Awesome - glad you got it working 😄  I actually experience that too... Climate device is also missing here 🤔 Maybe @jaroschek can help figure out what's wrong with that part? 🤞

**Comment by mgregersen** [comment]
Thanks for reply @jaroschek - and also for the great work you have done so far with this integration 👌 
I don't have the skills to develop things like this, so I think I'll also just use this integration for monitoring 😊

**Comment by gsolem** [comment]
Thanks @jaroschek and you are right the setup issue is resolved so I will close this issue. Thanks for the assistance and great work.
