### ISSUE TITLE
Debugging missing some writeable values

### ISSUE THREAD

**Issue by soulfire89** [jaroschek/home-assistant-myuplink#105]
Hey @jaroschek ,
I've bought myuplink premium manage today and I'm missing some writable values. I thought it would be possible to set all writeable values, but I only got these three when starting the integration:
![image](https://github.com/jaroschek/home-assistant-myuplink/assets/75139519/af1d4ca6-05ae-4130-9158-b7a1e46b6d33)

And I'm missing at least:
"parameterId": "40940",
    "parameterName": "Grad­minuten",

"parameterId": "50004",
    "parameterName": "Vorüber­gehen­der Luxus",
    "parameterUnit": "",
    "writable": true,

The values I'm missing in the **part /v2/devices/{deviceId}/points** are:
- Section: Ventilation Ventilationmodes. They are possible to set inside myuplink GUI:
![image](https://github.com/jaroschek/home-assistant-myuplink/assets/75139519/143f6d44-bd04-46c9-b45d-4b28dd6aa502)
I've found these information, when klicken the buttons inside the developementfunction of chrome. 
![image](https://github.com/jaroschek/home-assistant-myuplink/assets/75139519/c5666d91-5e6b-4608-a749-1b793832cd23)

- Section: Roomclimate: offset for supply line temperature:
![image](https://github.com/jaroschek/home-assistant-myuplink/assets/75139519/8c801f33-8ffe-412f-a951-ce720e2ef6b1)

![image](https://github.com/jaroschek/home-assistant-myuplink/assets/75139519/1d809081-8e51-4fd5-a225-39ac12faf5ca)

Would be really great if you find a possibility to integrate all values which are somehow not inside myuplink-API

**Comment by woopstar** [comment]
40940 and 50004 are provided by the API now. So the issue can be closed.
