### ISSUE TITLE
StrEnum Warning

### ISSUE THREAD

**Issue by RuneElleskov** [jaroschek/home-assistant-myuplink#115]
I got this in my log..

Logger: homeassistant.backports.enum
Source: helpers/deprecation.py:197
First occurred: 11:53:39 (1 occurrences)
Last logged: 11:53:39
StrEnum was used from myuplink, this is a deprecated alias which will be removed in HA Core 2025.5. Use enum.StrEnum instead, please report it to the author of the 'myuplink' custom integration

**Comment by jaroschek** [comment]
@RuneElleskov Thanks for the info regarding this deprecation warning.

I have updated the code to use `enum.StrEnum` instead.

The fix is published in the latest release: https://github.com/jaroschek/home-assistant-myuplink/releases/tag/1.2.4
