### ISSUE TITLE
Sorry, there was an error : unauthorized_client

### ISSUE THREAD

**Issue by piksliviksi** [jaroschek/home-assistant-myuplink#12]
I'm stuck, how to re-initate the setup, if https://api.myuplink.com/ gives an error?
I'd like to enter new identifier and the secret.

**Comment by 7RST1** [comment]
Go to the Devices & Services page, click the three dots top right and select "Application Credentials". Delete the one originating from myuplink, and you'll be prompted for credentials next time you set up myuplink :)

**Comment by folrewef** [comment]
I have tried resetting the application credentials several times but I still get the same error message.I even tried to create a new client secret. I copy and paste te credentials to avoid typing errors. 

I still get the unauthorized client error. Any idea what I could do wrong?

**Comment by jaroschek** [comment]
@piksliviksi could you solve your issue?

@folrewef I assume your question in this issue is a duplicate request to you own issue #23?

**Comment by folrewef** [comment]
Yes, wasn't sure you would see this one.

**Comment by piksliviksi** [comment]
I got my issue resolved, thanks
