### ISSUE TITLE
Missing writable values

### ISSUE THREAD

**Issue by matlimatli** [jaroschek/home-assistant-myuplink#122]
I noticed that some writable parameters are created as sensors instead of numbers. It seems like the API in some cases shows minValue and maxValue as null, causing find_fitting_entity() to return SENSOR instead of NUMBER. 

Example of such a parameter:
```
{
    "category": "F1155-16",
    "parameterId": "47669",
    "parameterName": "activated",
    "parameterUnit": "",
    "writable": true,
    "timestamp": "2024-07-16T10:49:23+00:00",
    "value": 1,
    "strVal": "1",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  }
```

I guess this is mainly a problem with the API. But as I suppose it might be hard to get that fixed; would a workaround be possible? Can a number exist without having a max or min value? The only parameters I care about with this problem are binaries (where the values 0 and 1 should be allowed). But I can see some other parameters, e.g. "Oper. time hot water", with the same issue, it is however a bit surprising that those are writable.

This might be related to #105

**Comment by woopstar** [comment]
I see the same issue here.

`47771` entity, which is the option to activate or deactivate the schema for the heating of houses in the schedules, for instance, is imported as a sensor, even though it's a switch on the MyUplink site.

**Comment by woopstar** [comment]
Following up with some additional debug information.

```
{
    "category": "METROAIR 330",
    "parameterId": "47771",
    "parameterName": "activated",
    "parameterUnit": "",
    "writable": true,
    "timestamp": "2024-08-01T13:19:08+00:00",
    "value": 0,
    "strVal": "0",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  }
  ```
  
  It looks like this should not be a sensor, since is `writable` . I am a bit unsure how to "detect" that his is a switch. Any ideas  @jaroschek  ?

**Comment by woopstar** [comment]
I can manually add it to 

https://github.com/jaroschek/home-assistant-myuplink/blob/main/custom_components/myuplink/const.py#L35

That could also resolve #105 ?
