### ISSUE TITLE
Large amount of entities

### ISSUE THREAD

**Issue by hedenolof** [jaroschek/home-assistant-myuplink#124]
NIBE F750 from 2015: I get a very large amount of control entities. In total (including sensors) I have 364 entities. See attached pictures for examples. 

Firmware F750: Firmware: 9701R3
Firmware MyUplink: 1.2.4

<img width="317" alt="Skärmavbild 2024-08-11 kl  09 47 37" src="https://github.com/user-attachments/assets/5dfeeee2-a28e-474e-b52a-a3a9dd8f376c">
<img width="338" alt="Skärmavbild 2024-08-11 kl  09 47 49" src="https://github.com/user-attachments/assets/c854948e-5262-4734-865c-4e17a8d40615">

**Comment by woopstar** [comment]
Yes. So what is the issue?

**Comment by hedenolof** [comment]
It gets very hard to manage, as can be see in the image it appears to exist doublets as well. When compared to a friend of mine with the same heat pump he doesn't have the same problem, he only has a handful of controls. 

Any suggestions of what could be wrong? 

Thanks!

**Comment by hedenolof** [comment]
Hi @jaroschek , sorry for my late reply. I will look into your solution. Thank you for your assistance.
