### ISSUE TITLE
Add integration to the default plugins in HACS

### ISSUE THREAD

**Issue by 7RST1** [jaroschek/home-assistant-myuplink#14]
I see you've already started the process of adding requirements for HACS submission. Seems like everything is ready.

Naturally, only the owner can submit a PR to hacs/default, so I wanted to ask if you think the repo is ready to do so? I think it is.

**Comment by jaroschek** [comment]
I have now startet the HACS submission through the following PR: https://github.com/hacs/default/pull/2105

Additionally I will start publishing releases following semantic versioning from now on.

**Comment by jaroschek** [comment]
The PR https://github.com/hacs/default/pull/2105 is finally merged.

The integration is now a default plugin in HACS.
