### ISSUE TITLE
Current (amperage) always showing 0.1A

### ISSUE THREAD

**Issue by Siggy101** [jaroschek/home-assistant-myuplink#147]
I have this nice integration running on my NIBE heat pump, via the SMO40.
I have many sensors giving data, and they have been for almost a year now, however I cannot get any meaningful data from the electricity current usage.
I see 3 sensors, one for each phase, but they all display "0.1A" at all times:
![image](https://github.com/user-attachments/assets/9f9ff391-df9d-4ab4-8ef1-e4d9e38a2bfd)
...and they never change their value, even when the heat pumps runs:
![image](https://github.com/user-attachments/assets/e361498c-a63f-4887-9dbd-565ab71a8a2c)

I have tried to follow the debugging instructions but I cannot get very far.  
Can anyone advise why these sensors are not showing the correct data, and how to fix it?

**Comment by Siggy101** [comment]
@jaroschek Are you able to confirm if this is a bug or config issue please?

**Comment by jaroschek** [comment]
@Siggy101 Unfortunately, I can neither confirm nor deny whether it is a bug until I know what data the API returns.

You should query your device data points as described in the README (https://github.com/jaroschek/home-assistant-myuplink#debugging-misbehaving-entities):

> Take note of the entity's name, and open [myUpLink's Swagger](https://api.myuplink.com/swagger/index.html).
> Click Authorize and paste your application credentials. Make sure to check the READSYSTEM box.
> Find your device ID by querying ​/v2​/systems​/me, and enter it when querying /v2/devices/{deviceId}/points.
> Find the relevant data points and post them in an issue.

You should past the relevant data for your current ampere sensor here.

**Comment by Siggy101** [comment]
HI @jaroschek 
Thanks for the pointers.  I had tried to follow the guide before I opened the bug, but I got it all wrong and couldn't get any output.
I tried again with a fresh head today, and it works.

I see the 3 current sensors BE1, BE2 and BE3 all read the same:

  {
    "category": "SMO 40",
    "parameterId": "40083",
    "parameterName": "Current (BE1)",
    "parameterUnit": "A",
    "writable": false,
    "timestamp": "2024-09-18T10:32:02+00:00",
    "value": 0.1,
    "strVal": "0.1A",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null

They are indeed returning data, but that data is always 0.1A.  This is what I see in Home Assistant too.
So, it looks like the integration is passing the data correctly to HA, but the data from the current sensors is always 0.1A.
Do you know why that would be?

**Comment by jaroschek** [comment]
Hi @Siggy101, unfortunately I have no information why the API delivers such values. But the myUplink API seems to be in development still and somtetimes it seems that the manufacturers are also responsible for problems.

May be you can somehow contact myUplink or the manufacturer of your device with that issue?

**Comment by fvdm** [comment]
I believe you need hardware probes installed and activated for those readings to appear. They are listed in the heatpump manual as if they come supplied, but mine doesn't have them and always show at `0.1A`.

**Comment by Siggy101** [comment]
> I believe you need hardware probes installed and activated for those readings to appear. They are listed in the heatpump service manual as if they come supplied, but mine doesn't have them and always show at `0.1A`.
> 
> ![image](https://private-user-images.githubusercontent.com/93784/369817601-dd3a5bfa-3392-4d36-90cf-978e77675870.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcxODI4NDAsIm5iZiI6MTcyNzE4MjU0MCwicGF0aCI6Ii85Mzc4NC8zNjk4MTc2MDEtZGQzYTViZmEtMzM5Mi00ZDM2LTkwY2YtOTc4ZTc3Njc1ODcwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNFQxMjU1NDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjdiNGYwMGRiNTQzNDljZTdlYjE4ZjhiMzQxYmFmN2NkMzIyZTc1NDNiYmY3NzdhMzBkZjZlNTI4YTM2ODVkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.1FdKp-XSTDRr50lFBlFhAytJ-FTMbDWDHyXPXWaiYDw)

Thank you so much for sharing that.  
It makes complete sense, and I wondered if I was missing some hardware (heatpump was installed by the previous owners).  It's really useful to know that you have the same 0.1A readings, and that kinda confirms it then.
The integration is working as expected, but not all installs have the hardware needed to create the readings.
