### ISSUE TITLE
More hot water isn't working anymore

### ISSUE THREAD

**Issue by martijnrusschen** [jaroschek/home-assistant-myuplink#169]
I'm using myuplink with a Nibe VVM S320 and S2125. Until last week I was able to trigger more hot water from the integration, but recently I'm seeing this error when toggling it: `Failed to perform the action switch/turn_on. 403, message='Forbidden', url='https://api.myuplink.com/v2/devices/<UUID>/points'` It seems something changed, and I'm not sure if it's in the myuplink API or since a recent integration release.

I already tried reinstalling the integration, but no luck yet.

**Comment by jaroschek** [comment]
@martijnrusschen I just tried the setting with my own S1255 and it worked without an issue.

The `403` error points to missing rights for writing properties. Did you recently authorized your integration again? You should check all the available options when authorizing your integration:
<img width="984" alt="image" src="https://github.com/user-attachments/assets/96ab837a-7791-4d4d-a725-471a754887dc">

**Comment by martijnrusschen** [comment]
It turned out my premium subscription had expired. The error message isn't very descriptive, sadly, so it took a while before I figured out what was going on.
