### ISSUE TITLE
Heat Meater values not updated with actual value

### ISSUE THREAD

**Issue by soulfire89** [jaroschek/home-assistant-myuplink#18]
My heat meater values were not updated correct. It has the value from mid july. Does any of the last updates affect these values?
![image](https://github.com/jaroschek/home-assistant-myuplink/assets/75139519/6a2adfc9-0aac-4837-9ac0-d2a07e68e1aa)

**Comment by 7RST1** [comment]
If they are writable through the API, they might have been redefined under Controls. They'd show up there instead in your device.

If you can't find them anywhere else, can you do a request of the data points response from the API directly and post them here?

Go to the [MyUplink Swagger site](https://api.myuplink.com/swagger/index.html), and authorize (top right).
Find your device ID by querying ​"/v2​/systems​/me", enter it when querying "/v2/devices/{deviceId}". Find the relevant data points and post them here.

**Comment by soulfire89** [comment]
Seems like it's not a tool issue. More an issue from myUplink. I wrote a ticket to the MyUplink service support.  
This issue could be onhold until we got the answer of MyUplink support.

"category": "Wärme­mengen­zähler",
    "parameterId": "44298",
    "parameterName": "Brauch­wasser, einschl. inter­ne ZH",
    "parameterUnit": "kWh",
    "writable": false,
    "timestamp": "2023-07-28T15:50:24+00:00",
    "value": 3119.6,
    "strVal": "3119.6kWh",
    "smartHomeCategories": [],
    "minValue": 0,
    "maxValue": 9999999,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Wärme­mengen­zähler",
    "parameterId": "44300",
    "parameterName": "Heizung, einschl. interne ZH",
    "parameterUnit": "kWh",
    "writable": false,
    "timestamp": "2023-07-28T15:50:24+00:00",
    "value": 14966.4,
    "strVal": "14966.4kWh",
    "smartHomeCategories": [],
    "minValue": 0,
    "maxValue": 9999999,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Wärme­mengen­zähler",
    "parameterId": "44306",
    "parameterName": "Brauch­wasser, nur Ver­dichter",
    "parameterUnit": "kWh",
    "writable": false,
    "timestamp": "2023-07-28T15:50:24+00:00",
    "value": 3104.2,
    "strVal": "3104.2kWh",
    "smartHomeCategories": [],
    "minValue": 0,
    "maxValue": 9999999,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Wärme­mengen­zähler",
    "parameterId": "44308",
    "parameterName": "Heizung, nur Ver­dichter",
    "parameterUnit": "kWh",
    "writable": false,
    "timestamp": "2023-07-28T15:50:24+00:00",
    "value": 13123.4,
    "strVal": "13123.4kWh",
    "smartHomeCategories": [],
    "minValue": 0,
    "maxValue": 9999999,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },

**Comment by soulfire89** [comment]
There was an Firmwareupdate to Version 9586R4 today. Now every datapoint is available again. Issue can be closed.

**Comment by jaroschek** [comment]
I'm glad your problem was solved.
