### ISSUE TITLE
Sorry, there was an error : invalid_request

### ISSUE THREAD

**Issue by folrewef** [jaroschek/home-assistant-myuplink#23]
I have reset the application credentials. I then restarted Home Assistant. I entered the credentials but still get the invalid request error.

What can I have done wrong?

**Comment by jaroschek** [comment]
Hello, the "invalid request" seems familiar. May be you have the same problems as described and answered in here: https://github.com/jaroschek/home-assistant-myuplink/issues/1#issuecomment-1312222671

So please check your redirect url when creating the application in dev.myuplink.com. Also don't try to change the url in an existing application as I experienced that this does not work. If you need a different redirect url for authentication you have to create a new application. 

Hope this helps.

**Comment by folrewef** [comment]
Resolved. The redirect url was the problem. Many thanks.
