### ISSUE TITLE
API Invalid Request

### ISSUE THREAD

**Issue by Axser89** [jaroschek/home-assistant-myuplink#30]
Hello, so i've setup integration but keep getting invalid request while adding integration.
Is there a way to reconfigure identificator and secret? Or a way to change request to myuplink?

**Comment by b1czu** [comment]
> Is there a way to reconfigure identificator and secret?

OAuth secrets are stored in `application_credentials` file inside `.storage` dir in your HA configuration directory. It could also be accessed by UI in _Settings -> Devices & Services -> [3 Dots hamburger menu] -> Application Credentials_. Uninstalling myUplink integration does not remove OAuth secrets so you won't be asked to provide them when reinstalling / reconfiguring integration.
