### ISSUE TITLE
No reconfiguration of integration possible

### ISSUE THREAD

**Issue by kusk** [jaroschek/home-assistant-myuplink#39]
Issue:
If I have configured the integration with a wrong callback URL, I have no way of reconfiguring the integration with a new callback URL+ID+secret.

Steps to reproduce:
1. Install integration from HACS.
2. Configure integration with wrong callback URL.
3. Everytime the integration is added under "Integration" the website "https://api.myuplink.com/oauth/error?errorId=CfD...." is opened.
4. Removal and reinstall of integration doesnt wipe the configuration.

**Comment by jaroschek** [comment]
Please remove the stored application credentials for the integration to re-authorize the access to the myUplink api.

This was already discussed in #30:

> > Is there a way to reconfigure identificator and secret?
> 
> OAuth secrets are stored in `application_credentials` file inside `.storage` dir in your HA configuration directory. It could also be accessed by UI in _Settings -> Devices & Services -> [3 Dots hamburger menu] -> Application Credentials_. Uninstalling myUplink integration does not remove OAuth secrets so you won't be asked to provide them when reinstalling / reconfiguring integration.

**Comment by kusk** [comment]
Ah missed that. Awesome it works now and it even pulls power usage unlike the old plugin.

**Comment by kusk** [comment]
Ah missed that. Awesome it works now and it even pulls power usage unlike the old plugin.
