### ISSUE TITLE
Missing sensors

### ISSUE THREAD

**Issue by Seekersdk** [jaroschek/home-assistant-myuplink#40]
Hi,

Thank you for your work. I got everything setup and working, but Ive noticed I am missing some sensors I used to have in the NibeUplink intergation. Are there an somewhat easy way for me to add these without a ton of hassel, or do you need to do it?

  {
    "category": "Slave 1 (EB101)",
    "parameterId": "44703",
    "parameterName": "Defrost­ing (EB101-EP14)",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2023-12-13T03:37:02+00:00",
    "value": 0,
    "strVal": "0",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  },

  {
    "category": "Slave 1 (EB101)",
    "parameterId": "40782",
    "parameterName": "Re­quested com­pressor freq (EB101)",
    "parameterUnit": "Hz",
    "writable": false,
    "timestamp": "2023-12-13T03:37:02+00:00",
    "value": 0,
    "strVal": "0Hz",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  },
{
    "category": "Slave 1 (EB101)",
    "parameterId": "44701",
    "parameterName": "Current com­pressor fre­quency (EB101)",
    "parameterUnit": "Hz",
    "writable": false,
    "timestamp": "2023-12-13T03:37:02+00:00",
    "value": 0,
    "strVal": "0Hz",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },

**Comment by jaroschek** [comment]
Are these 3 parameters available in your parameters response from the myUplink API?

> You can do a request of the data points from the API directly and post the response here.
>
> Go to the [MyUplink Swagger site](https://api.myuplink.com/swagger/index.html), and authorize (top right).
> Find your device ID by querying ​"/v2​/systems​/me", enter it when querying "/v2/devices/{deviceId}/points". 
> Find the relevant data point(s) and post the response here.

This integration should create an entity for every parameter that is provided in the response.

If the parameters are missing in the response from the myUplink API, we have no chance.

But if the above parameters are already provided by the myUplink API but the entities are missing, then there seems to be a bug in the integration that has to be solved.

Can you please confirm, if the parameters are already provided in the myUplink API?

**Comment by jaroschek** [comment]
I have just checked with my own installation. I have a similar parameter with unit `Hz`:
```
{
    "category": "NIBE S1255-6 E PC EM 3X400V",
    "parameterId": "5927",
    "parameterName": "Current compres­sor fre­quency",
    "parameterUnit": "Hz",
    "writable": false,
    "timestamp": "2023-12-20T13:38:48+00:00",
    "value": 90,
    "strVal": "90Hz",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  }
```
The entity for this parameter is created already. So there is currently no bug I could reproduce, that would prevent your entity. But as the entity is showing a frequency I added support for the matching device class:

<img width="471" alt="image" src="https://github.com/jaroschek/home-assistant-myuplink/assets/470290/3380f762-5a77-4636-b7f0-504b562518e2">

**Comment by jaroschek** [comment]
Just a quick additional note:

Based on the parameter name and category your entities should have the following names:
- `Slave 1 (EB101) Defrost­ing (EB101-EP14)`
- `Slave 1 (EB101) Re­quested com­pressor freq (EB101)`
- `Slave 1 (EB101) Current com­pressor fre­quency (EB101)`

The naming of the entities is using the given category to group the entities by category name.

**Comment by Cicrocoft** [comment]
The sensors showed up the day after. I found them all :-) 

Thanks for the reply and your work. 
I'm the same as above/thread starter, btw

**Comment by jaroschek** [comment]
Thank you for your Feedback. I'm grad it's Working for you now.
