### ISSUE TITLE
Myuplink error: Sorry, there was an error : unauthorized_client

### ISSUE THREAD

**Issue by Matmarknaden** [jaroschek/home-assistant-myuplink#49]
I have made an unsuccesfull reinstallation (removal and new installation) of "myuplink". Also removed old myuplink secrets and created new ones. However now not able to install the custom integration again, when authorization to api.myuplink.com I recieve "Error Sorry, there was an error : unauthorized_client". Assume the old client ID and secret still is used at authentification, cannot  find where these are stored (no such thing in in configuration.yaml)

**Comment by jaroschek** [comment]
Please remove the stored application credentials for the integration to re-authorize the access to the myUplink api.

> > Is there a way to reconfigure identificator and secret?
> 
> OAuth secrets are stored in `application_credentials` file inside `.storage` dir in your HA configuration directory. It could also be accessed by UI in _Settings -> Devices & Services -> [3 Dots hamburger menu] -> Application Credentials_. Uninstalling myUplink integration does not remove OAuth secrets so you won't be asked to provide them when reinstalling / reconfiguring integration.
