### ISSUE TITLE
Connection partly fails with Home Assistant 2024.1.2 

### ISSUE THREAD

**Issue by karimononen** [jaroschek/home-assistant-myuplink#55]
Anyone else having problems with the Core v. 2024.1.2, Operating system v. 11.4?

Everything worked like charm before the update. 

Now the connection with the myuplink API works only partly. It can get the initial values but then the value updates fail.

The logbook says  "xxx became unavailable" for all sensors after setting up the integration.

I have removed and recreated new application several times in dev.myuplink.com/apps service and re-installed the home assistant integration to get a fresh restart.

![myuplink](https://github.com/jaroschek/home-assistant-myuplink/assets/89708880/8b51ca6e-8393-4a19-98b1-1739f722a715)

**Comment by 7RST1** [comment]
I just updated mine to 2024.1.2 as well, but I haven't had any issues so far.

Does the debug-log say anything?

**Comment by karimononen** [comment]
Hello 7RST1,
I get two errormessages while setting up the integration.
They don't look fatal to me but I'm not familiar with the mechanics of this integration.


Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:368
Integration: Sensor (documentation, issues)
First occurred: 05:22:54 (1 occurrences)
Last logged: 05:22:54

Error while setting up myuplink platform for sensor
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 368, in _async_setup_platform
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 618, in state
    raise ValueError(
ValueError: Sensor sensor.ctc_ecozenith_i255_general_mixing_valve_delay provides state value '0', which is not in the list of options provided


and


Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 05:22:54 (1 occurrences)
Last logged: 05:22:54

Error adding entities for domain sensor with platform myuplink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 618, in state
    raise ValueError(
ValueError: Sensor sensor.ctc_ecozenith_i255_general_mixing_valve_delay provides state value '0', which is not in the list of options provided

**Comment by karimononen** [comment]
Another funny thing is that the trends seem to stay stored somewhere even if I delete the device.

I can see the history of the entity values time before I installed the integration. The data must be from earlier installation.

I deleted the device and restarted HA in between.

**Comment by karimononen** [comment]
Third error message

Logger: homeassistant.components.sensor
Source: helpers/entity_platform.py:507
Integration: Sensor (documentation, issues)
First occurred: 05:22:54 (1 occurrences)
Last logged: 05:22:54

Error adding entities for domain sensor with platform myuplink
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1278, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 941, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1062, in _async_write_ha_state
    state, attr, capabilities, shadowed_attr = self.__async_calculate_state()
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 999, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 947, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 618, in state
    raise ValueError(
ValueError: Sensor sensor.ctc_ecozenith_i255_general_mixing_valve_delay provides state value '0', which is not in the list of options provided

**Comment by jaroschek** [comment]
Hello @karimononen, 

the errors seem to point to a parameter/entity that may be defined as `enum` using predefined values from api as options. But somehow a value is provided that is not available in the given list of options.

The enum options are provided as part of the response of `/v2/devices/{deviceId}/points` like in the following example:

```
  {
    "category": "NIBE S1255-6 E PC EM 3X400V",
    "parameterId": "55000",
    "parameterName": "Priority",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-12T04:12:08+00:00",
    "value": 20,
    "strVal": "Hot water",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "10",
        "text": "Off",
        "icon": ""
      },
      {
        "value": "20",
        "text": "Hot water",
        "icon": ""
      },
      {
        "value": "25",
        "text": "Ext. hot water",
        "icon": ""
      },
      {
        "value": "30",
        "text": "Heating",
        "icon": ""
      },
      {
        "value": "40",
        "text": "Pool",
        "icon": ""
      },
      {
        "value": "41",
        "text": "Pool 2",
        "icon": ""
      },
      {
        "value": "50",
        "text": "Transfer",
        "icon": ""
      },
      {
        "value": "60",
        "text": "Cooling",
        "icon": ""
      }
    ],
    "scaleValue": "1",
    "zoneId": null
  },
```
Here also is no option with value `0` and the property value should also never contain a value `0`.

Can you try and check the direct API response of the parameter points?

Go to the MyUplink Swagger site, and authorize (top right). Find your device ID by querying `​/v2​/systems​/me`, enter it when querying `/v2/devices/{deviceId}/points`.

Can you please paste the parameter points response here, so we can take a look?

**Comment by karimononen** [comment]
Hello jaroschek,
Very kind of you to help me! Appreciated!

Here is the response from swagger that you asked:

[
  {
    "category": "Hot water",
    "parameterId": "61500",
    "parameterName": "Hot water mode",
    "parameterUnit": "",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 0,
    "strVal": "Economy",
    "smartHomeCategories": [],
    "minValue": 0,
    "maxValue": 3,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "0",
        "text": "Economy",
        "icon": ""
      },
      {
        "value": "1",
        "text": "Normal",
        "icon": ""
      },
      {
        "value": "2",
        "text": "Comfort",
        "icon": ""
      }
    ],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "Hot water",
    "parameterId": "61501",
    "parameterName": "Stop temp HP setpoint",
    "parameterUnit": "°C",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 57,
    "strVal": "57°C",
    "smartHomeCategories": [],
    "minValue": 400,
    "maxValue": 590,
    "stepValue": 10,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Hot water",
    "parameterId": "61503",
    "parameterName": "Extra hot water",
    "parameterUnit": "h",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 0,
    "strVal": "0h",
    "smartHomeCategories": [],
    "minValue": 0,
    "maxValue": 20,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.5",
    "zoneId": null
  },
  {
    "category": "Heat pump settings",
    "parameterId": "61504",
    "parameterName": "Max time heating",
    "parameterUnit": "min",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 20,
    "strVal": "20min",
    "smartHomeCategories": [],
    "minValue": 10,
    "maxValue": 120,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "Heat pump settings",
    "parameterId": "61505",
    "parameterName": "Max time hot water",
    "parameterUnit": "min",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 60,
    "strVal": "60min",
    "smartHomeCategories": [],
    "minValue": 10,
    "maxValue": 150,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "General",
    "parameterId": "61508",
    "parameterName": "Holiday period",
    "parameterUnit": "days",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 0,
    "strVal": "0days",
    "smartHomeCategories": [],
    "minValue": 0,
    "maxValue": 300,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "Heating circuit 1",
    "parameterId": "61513",
    "parameterName": "Inclination",
    "parameterUnit": "",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 43,
    "strVal": "43",
    "smartHomeCategories": [],
    "minValue": 250,
    "maxValue": 850,
    "stepValue": 10,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heating circuit 1",
    "parameterId": "61517",
    "parameterName": "Adjustment",
    "parameterUnit": "",
    "writable": true,
    "timestamp": "2024-01-11T16:35:39+00:00",
    "value": 8,
    "strVal": "8",
    "smartHomeCategories": [],
    "minValue": -200,
    "maxValue": 200,
    "stepValue": 10,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Add. heat",
    "parameterId": "61590",
    "parameterName": "Lower immersion heater / heating kW",
    "parameterUnit": "",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 6,
    "strVal": "6",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "0",
        "text": "0.0",
        "icon": ""
      },
      {
        "value": "60",
        "text": "6.0",
        "icon": ""
      },
      {
        "value": "90",
        "text": "9.0",
        "icon": ""
      }
    ],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Add. heat",
    "parameterId": "61591",
    "parameterName": "Upper immersion heater / DHW kW",
    "parameterUnit": "",
    "writable": true,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 5.5,
    "strVal": "5.5",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "0",
        "text": "0.0",
        "icon": ""
      },
      {
        "value": "3",
        "text": "0.3",
        "icon": ""
      },
      {
        "value": "6",
        "text": "0.6",
        "icon": ""
      },
      {
        "value": "9",
        "text": "0.9",
        "icon": ""
      },
      {
        "value": "12",
        "text": "1.2",
        "icon": ""
      },
      {
        "value": "15",
        "text": "1.5",
        "icon": ""
      },
      {
        "value": "18",
        "text": "1.8",
        "icon": ""
      },
      {
        "value": "21",
        "text": "2.1",
        "icon": ""
      },
      {
        "value": "23",
        "text": "2.3",
        "icon": ""
      },
      {
        "value": "26",
        "text": "2.6",
        "icon": ""
      },
      {
        "value": "29",
        "text": "2.9",
        "icon": ""
      },
      {
        "value": "32",
        "text": "3.2",
        "icon": ""
      },
      {
        "value": "35",
        "text": "3.5",
        "icon": ""
      },
      {
        "value": "38",
        "text": "3.8",
        "icon": ""
      },
      {
        "value": "41",
        "text": "4.1",
        "icon": ""
      },
      {
        "value": "44",
        "text": "4.4",
        "icon": ""
      },
      {
        "value": "46",
        "text": "4.6",
        "icon": ""
      },
      {
        "value": "49",
        "text": "4.9",
        "icon": ""
      },
      {
        "value": "52",
        "text": "5.2",
        "icon": ""
      },
      {
        "value": "55",
        "text": "5.5",
        "icon": ""
      },
      {
        "value": "58",
        "text": "5.8",
        "icon": ""
      },
      {
        "value": "61",
        "text": "6.1",
        "icon": ""
      },
      {
        "value": "64",
        "text": "6.4",
        "icon": ""
      },
      {
        "value": "67",
        "text": "6.7",
        "icon": ""
      },
      {
        "value": "69",
        "text": "6.9",
        "icon": ""
      },
      {
        "value": "72",
        "text": "7.2",
        "icon": ""
      },
      {
        "value": "75",
        "text": "7.5",
        "icon": ""
      },
      {
        "value": "78",
        "text": "7.8",
        "icon": ""
      },
      {
        "value": "81",
        "text": "8.1",
        "icon": ""
      },
      {
        "value": "84",
        "text": "8.4",
        "icon": ""
      },
      {
        "value": "87",
        "text": "8.7",
        "icon": ""
      },
      {
        "value": "90",
        "text": "9.0",
        "icon": ""
      }
    ],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "General",
    "parameterId": "62000",
    "parameterName": "Outdoor Temperature",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T17:44:46+00:00",
    "value": -7,
    "strVal": "-7°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Hot water",
    "parameterId": "62001",
    "parameterName": "Stop temp HP current",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 57,
    "strVal": "57°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "General",
    "parameterId": "62004",
    "parameterName": "Mixing valve delay",
    "parameterUnit": "min",
    "writable": false,
    "timestamp": "2024-01-12T17:44:46+00:00",
    "value": 30,
    "strVal": "30min",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "241",
        "text": "Blocked",
        "icon": ""
      }
    ],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "General",
    "parameterId": "62005",
    "parameterName": "Status",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-12T17:44:46+00:00",
    "value": 1,
    "strVal": "HP lower",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "0",
        "text": "HP upper",
        "icon": ""
      },
      {
        "value": "1",
        "text": "HP lower",
        "icon": ""
      },
      {
        "value": "2",
        "text": "Add. heat",
        "icon": ""
      },
      {
        "value": "3",
        "text": "HP + Add. heat",
        "icon": ""
      },
      {
        "value": "4",
        "text": "HC",
        "icon": ""
      },
      {
        "value": "5",
        "text": "DHW",
        "icon": ""
      },
      {
        "value": "6",
        "text": "Pool",
        "icon": ""
      },
      {
        "value": "7",
        "text": "Off",
        "icon": ""
      },
      {
        "value": "8",
        "text": "HC mixing",
        "icon": ""
      },
      {
        "value": "9",
        "text": "Wood",
        "icon": ""
      },
      {
        "value": "10",
        "text": "DHW/HC",
        "icon": ""
      },
      {
        "value": "11",
        "text": "Cooling",
        "icon": ""
      },
      {
        "value": "12",
        "text": "Swap",
        "icon": ""
      }
    ],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "General",
    "parameterId": "62006",
    "parameterName": "Radiator temp",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T18:04:46+00:00",
    "value": 49,
    "strVal": "49°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heating circuit 1",
    "parameterId": "62007",
    "parameterName": "Primary flow setpoint",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T17:44:46+00:00",
    "value": 47,
    "strVal": "47°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heating circuit 1",
    "parameterId": "62011",
    "parameterName": "Primary flow temp",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T18:04:46+00:00",
    "value": 45,
    "strVal": "45°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heating circuit 1",
    "parameterId": "62015",
    "parameterName": "Return flow",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T17:59:46+00:00",
    "value": 31,
    "strVal": "31°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heat pump 1",
    "parameterId": "62017",
    "parameterName": "Status",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-12T17:59:46+00:00",
    "value": 0,
    "strVal": "Off, start delay",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "0",
        "text": "Off, start delay",
        "icon": ""
      },
      {
        "value": "1",
        "text": "Off, ready to start",
        "icon": ""
      },
      {
        "value": "2",
        "text": "Wait until flow",
        "icon": ""
      },
      {
        "value": "3",
        "text": "On",
        "icon": ""
      },
      {
        "value": "4",
        "text": "Defrost",
        "icon": ""
      },
      {
        "value": "5",
        "text": "Cooling",
        "icon": ""
      },
      {
        "value": "6",
        "text": "Blocked",
        "icon": ""
      },
      {
        "value": "7",
        "text": "Off, alarm",
        "icon": ""
      },
      {
        "value": "8",
        "text": "Function test",
        "icon": ""
      },
      {
        "value": "30",
        "text": "Not defined",
        "icon": ""
      },
      {
        "value": "31",
        "text": "Comp. disabled",
        "icon": ""
      },
      {
        "value": "32",
        "text": "Comm. error",
        "icon": ""
      },
      {
        "value": "33",
        "text": "Hot water",
        "icon": ""
      }
    ],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "Heat pump 1",
    "parameterId": "62027",
    "parameterName": "HP in",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T18:04:46+00:00",
    "value": 45,
    "strVal": "45°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heat pump 1",
    "parameterId": "62037",
    "parameterName": "HP out",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T18:04:46+00:00",
    "value": 46,
    "strVal": "46°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heat pump 1",
    "parameterId": "62107",
    "parameterName": "Charge pump",
    "parameterUnit": "%",
    "writable": false,
    "timestamp": "2024-01-12T15:29:43+00:00",
    "value": 25,
    "strVal": "25%",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heat pump 1",
    "parameterId": "62147",
    "parameterName": "Outdoor Temperature HP",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T18:04:46+00:00",
    "value": -5,
    "strVal": "-5°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heat pump 1",
    "parameterId": "62157",
    "parameterName": "Software version",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 23490,
    "strVal": "23490",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "Add. heat",
    "parameterId": "62168",
    "parameterName": "Electric power kW",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-12T16:19:44+00:00",
    "value": 0,
    "strVal": "0",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Add. heat",
    "parameterId": "62169",
    "parameterName": "Electric power kW: Heating",
    "parameterUnit": "kW",
    "writable": false,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 0,
    "strVal": "0kW",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Heat pump 1",
    "parameterId": "62234",
    "parameterName": "Operation time/24h HP1",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-11T21:44:23+00:00",
    "value": 1094,
    "strVal": "1094",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "General",
    "parameterId": "62244",
    "parameterName": "Software version",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 20210629,
    "strVal": "20210629",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "Heating circuit 1",
    "parameterId": "62246",
    "parameterName": "Status",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 3,
    "strVal": "On",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "0",
        "text": "Heating off",
        "icon": ""
      },
      {
        "value": "1",
        "text": "Holiday",
        "icon": ""
      },
      {
        "value": "2",
        "text": "Night reduction",
        "icon": ""
      },
      {
        "value": "3",
        "text": "On",
        "icon": ""
      },
      {
        "value": "4",
        "text": "Cooling",
        "icon": ""
      }
    ],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "General",
    "parameterId": "62253",
    "parameterName": "Product",
    "parameterUnit": "",
    "writable": false,
    "timestamp": "2024-01-09T20:00:56+00:00",
    "value": 39,
    "strVal": "CTC EcoZenith i255",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [
      {
        "value": "0",
        "text": "CTC Ecologic",
        "icon": ""
      },
      {
        "value": "1",
        "text": "CTC EcoZenith i550 Pro",
        "icon": ""
      },
      {
        "value": "2",
        "text": "CTC EcoZenith i250",
        "icon": ""
      },
      {
        "value": "3",
        "text": "CTC EcoHeat 400",
        "icon": ""
      },
      {
        "value": "4",
        "text": "CTC GSi 12",
        "icon": ""
      },
      {
        "value": "5",
        "text": "CTC EcoZenith i350",
        "icon": ""
      },
      {
        "value": "6",
        "text": "CTC GSi 12 (BE)",
        "icon": ""
      },
      {
        "value": "7",
        "text": "CTC GS 6",
        "icon": ""
      },
      {
        "value": "8",
        "text": "CTC GS 8",
        "icon": ""
      },
      {
        "value": "9",
        "text": "CTC EcoZenith i350FL",
        "icon": ""
      },
      {
        "value": "10",
        "text": "CTC GSi 16",
        "icon": ""
      },
      {
        "value": "11",
        "text": "CTC GSi 8",
        "icon": ""
      },
      {
        "value": "12",
        "text": "CTC EcoLogic Pro",
        "icon": ""
      },
      {
        "value": "13",
        "text": "CTC EcoLogic M",
        "icon": ""
      },
      {
        "value": "14",
        "text": "CTC EcoLogic L",
        "icon": ""
      },
      {
        "value": "15",
        "text": "CTC EcoPart 400 Pro",
        "icon": ""
      },
      {
        "value": "16",
        "text": "CTC EcoZenith I550 Pro",
        "icon": ""
      },
      {
        "value": "17",
        "text": "CTC EcoZenith I555 Pro",
        "icon": ""
      },
      {
        "value": "18",
        "text": "CTC EcoLogic S",
        "icon": ""
      },
      {
        "value": "19",
        "text": "CTC GSi 8",
        "icon": ""
      },
      {
        "value": "20",
        "text": "CTC GSi 12",
        "icon": ""
      },
      {
        "value": "21",
        "text": "CTC GSi 12 (BE)",
        "icon": ""
      },
      {
        "value": "22",
        "text": "CTC GSi 16",
        "icon": ""
      },
      {
        "value": "23",
        "text": "CTC GSi 608",
        "icon": ""
      },
      {
        "value": "24",
        "text": "CTC GSi 612",
        "icon": ""
      },
      {
        "value": "25",
        "text": "CTC GSi 616",
        "icon": ""
      },
      {
        "value": "26",
        "text": "CTC GS 6",
        "icon": ""
      },
      {
        "value": "27",
        "text": "CTC GS 8",
        "icon": ""
      },
      {
        "value": "28",
        "text": "CTC GS 606",
        "icon": ""
      },
      {
        "value": "29",
        "text": "CTC GS 608",
        "icon": ""
      },
      {
        "value": "30",
        "text": "CTC EcoZenith i350",
        "icon": ""
      },
      {
        "value": "31",
        "text": "CTC EcoZenith i360",
        "icon": ""
      },
      {
        "value": "32",
        "text": "CTC EcoVent i350F",
        "icon": ""
      },
      {
        "value": "33",
        "text": "CTC EcoVent i360F",
        "icon": ""
      },
      {
        "value": "34",
        "text": "CTC EcoHeat 406",
        "icon": ""
      },
      {
        "value": "35",
        "text": "CTC EcoHeat 408",
        "icon": ""
      },
      {
        "value": "36",
        "text": "CTC EcoHeat 410",
        "icon": ""
      },
      {
        "value": "37",
        "text": "CTC EcoHeat 412",
        "icon": ""
      },
      {
        "value": "38",
        "text": "CTC EcoZenith i250",
        "icon": ""
      },
      {
        "value": "39",
        "text": "CTC EcoZenith i255",
        "icon": ""
      },
      {
        "value": "40",
        "text": "CTC EcoHeat 400",
        "icon": ""
      },
      {
        "value": "41",
        "text": "CTC EcoLogic Family",
        "icon": ""
      },
      {
        "value": "1041",
        "text": "Aeroheat CM Wandregler",
        "icon": ""
      },
      {
        "value": "1014",
        "text": "Aeroheat CM Wandregler 2.0",
        "icon": ""
      },
      {
        "value": "1030",
        "text": "CM Hydrauliktower 12",
        "icon": ""
      },
      {
        "value": "1031",
        "text": "CM Hydrauliktower 12.1",
        "icon": ""
      },
      {
        "value": "2000",
        "text": "Høiax Anima ECO Controller",
        "icon": ""
      },
      {
        "value": "2005",
        "text": "Høiax Anima ECO Tower",
        "icon": ""
      },
      {
        "value": "2041",
        "text": "Høiax Anima ECO Controller",
        "icon": ""
      },
      {
        "value": "2014",
        "text": "Høiax Anima ECO Controller 3000",
        "icon": ""
      },
      {
        "value": "2030",
        "text": "Høiax Anima ECO Tower",
        "icon": ""
      },
      {
        "value": "2031",
        "text": "Høiax Anima ECO Tower 3000",
        "icon": ""
      }
    ],
    "scaleValue": "1",
    "zoneId": null
  },
  {
    "category": "General",
    "parameterId": "62274",
    "parameterName": "Radiator setpoint",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T17:44:46+00:00",
    "value": 52,
    "strVal": "52°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  },
  {
    "category": "Hot water",
    "parameterId": "62276",
    "parameterName": "Hot water tank temp",
    "parameterUnit": "°C",
    "writable": false,
    "timestamp": "2024-01-12T18:04:46+00:00",
    "value": 57,
    "strVal": "57°C",
    "smartHomeCategories": [],
    "minValue": null,
    "maxValue": null,
    "stepValue": 1,
    "enumValues": [],
    "scaleValue": "0.1",
    "zoneId": null
  }
]

**Comment by karimononen** [comment]
Sorry! Should have added that data as a file...

**Comment by karimononen** [comment]
Hello @jaroschek ,

Thanks, the integration works again!
Very happy that you fixed it so soon!

Cheers!
