### ISSUE TITLE
Error creating Application on dev.myuplink.com

### ISSUE THREAD

**Issue by cnestande** [jaroschek/home-assistant-myuplink#9]
Hi,
Not really a bug with your code, but when I try to add a new application to dev.myuplink.com I get an error:
`Callback Url must be a valid URL`
I have entered the following callback url: https://my.home-assistant.io/redirect/oauth

![Screenshot 2023-06-12 at 12 56 59](https://github.com/jaroschek/home-assistant-myuplink/assets/53866502/78d220bf-c0be-47ce-84af-49cc88169ab8)

Any idea on how I can resolve the issue?

**Comment by soulfire89** [comment]
Same issue here. I think you need to replace "my.home-assistant.io" with your Homeassistant IP, but I'm new to it and not 100% sure

**Comment by soulfire89** [comment]
yes, i did it, follow instruction from here https://dev.myuplink.com/

But I'm struggling with the next step....

**Comment by soulfire89** [comment]
@jaroschek Do you think it will be possible to get a more detailed instruction up to the picture from your example?

**Comment by bever66** [comment]
@jaroschek Same here, "https://my.home-assistant.io/redirect/oauth" isn't accepted in the myuplink application setup and filling in the IP address does not work either. A solution would be appreciated. Thanks in advance!

**Comment by soulfire89** [comment]
try it with this Link **http://home-assistantipadresse:8123/redirect/oauth**and change _**home-assistantipadresse**_ into yours. 

Some of the requests work at https://api.myuplink.com/swagger/index.html, but I have no idea how to work with this inside home-assistant.

**Comment by jaroschek** [comment]
Hello, I have to admit that I#M quiter busy at work currently and don't have much time to view into this issue. But I hope I can clarify these newly problems.

First of all this all was working like expected, some weeks ago. I could setup this whole integration using the standard callback-url from Home Assistant that you tried: https://my.home-assistant.io/redirect/oauth

Unfortunately the developers at myUplink seem to have added some restricted validation to the form where you can create an application.

The form is currently build in this javascript: https://dev.myuplink.com/static/js/pages/Apps/components/CreateNewAppForm/CreateNewAppForm.js

There it references a `callbackURLRegex` at line 29. This regex is then provided by this javascript: https://dev.myuplink.com/static/js/components/constants/constants.js
`export const callbackURLRegex = /^https?:\/\/\w+(\.\w+)*(:[0-9]+)?(\/.*)?$/;`

So it does allow multiple combinations of words for the host/domain.

BUT: It does NOT allow any signs like the dash `-` that is right in the middle of `home-assistant`.

That is currently a limitation only the developers of the developer-portal from myUplink can fix.

We have to try to use the support to file an issue to get this solved.

Until then can we only successfully create a new application there by using host-/domain-names with whole word.

**Comment by jaroschek** [comment]
Hello @soulfire89, regarding your problem with the invalid request... this seems to be the same as in the first issue https://github.com/jaroschek/home-assistant-myuplink/issues/1

I think the main problem here was, that you can not (successfully) change the callback-url of an existing application in the developer-portal for myUplink. If you want to change the callback-url (perhaps for testing reasons), you will have to create a new application. And to not confuse your Home Assistant installation, you should also delete any saved credentials for the myUplink integration there.

**Comment by soulfire89** [comment]
> BUT: It does NOT allow any signs like the dash `-` that is right in the middle of `home-assistant`.

I can confirm that. After deleting "-" between home-assistant. It will unshow the "Callback Url must be a valid URL", but it won't work without "-"

Support mail with your previous information about changes policy is out: gdpr@myuplink.com

**Comment by cnestande** [comment]
I have also reported it to myUplink from the contacts page on the “non-developer” login. There is a form I filled out. I got a response that the developers have been notified. Hopefully it is a quick fix, I assume this is only frontend…

**Comment by soulfire89** [comment]
>  Hi and thank you for contacting Team NIBE Uplink!
> Unfortunately, we currently have a bug that does not allow hyphens, but we thank you for your feedback and expect it to be resolved within a week or so, we must apologize if it causes problems for you.

 Seems like it's allready ongoing.

**Comment by bever66** [comment]
I wonder if the "-" character is the only issue. I use my own domain name which is straight foward without any dash whatsoever and I still get the "invalid request" response from myuplink.

**Comment by supergregg** [comment]
> 

I think you get that because Homeassistant hard codes every oauth to pass through the my.home-assistan.io site. You can see that if you go back to HA after the "invalid request" and copy the URL from the "Open page" button. The Link there does not use your local URL. I tried manipulating this link, entering my internet facing HA, that results in getting a screen from MyUplink requesting access (as expected). But Pressing Yes, just results in an Error message back in HA, guessing due to the manipulated URLs. The Only way to disable the my.home-assistant.io is to break apart the "default_config:" and exclude "My Home Assistant " and that is a bit of a pain as it needs to be maintained.

**Comment by AbsolutJohan** [comment]
This has been fixed on their end today and you can use https://my.home-assistant.io/redirect/oauth as callback URL again 😀

**Comment by soulfire89** [comment]
Problem solved!

**Comment by cnestande** [comment]
Yes, I also made it work today. I'll close the ticket.
