### ISSUE TITLE
Don't update sensors to unavailable on uplink timeout (?)

### ISSUE THREAD

**Issue by elden1337** [jaroschek/home-assistant-myuplink#96]
A couple of times a day I get timeout from myuplink. Given the prev instructions on set update freq I interpreted mine as being ok for 60s, so that's what its at. 
And if the issue was temp overusage it would say that, right?

So, my question is, wouldnt it be better to not update the sensors to unavailable when these timeouts occur, but rather keep the latest known and continue fetching again later?

**Comment by abbamust** [comment]
I have same problem.
Not all sensor at once, but after some time many sensors are unavailible.
I can load the integration agian, and every sensor is ok again...

**Comment by fsedarkalex** [comment]
Also having the issue here, that myuplink seems to be timeouting from time to time. Maybe the "unavailable" flag can be delayd to for example only if it fails X times in a row?

**Comment by elden1337** [comment]
@jaroschek i have thought a bit about digging into this myself and see if i can find out why. 
Do you have any ideas to this? it's quite often it turns unavailable still, just an example from last hours from here: 

<img width="356" alt="image" src="https://github.com/user-attachments/assets/e684ed4c-f7ba-4af7-a8eb-377372de7e45">

**Comment by jaroschek** [comment]
@elden1337 I have noticed this myself. 

What version are you running? I'm currently debugging hourly reloads that seem to occour with the latest version 1.3.0.

**Comment by elden1337** [comment]
Latest

**Comment by jaroschek** [comment]
I just found, that the hourly token refresh for the oauth2 api requests forces the integration to reload the config entry.

This was introduced with #138 to automatically reload the config entry after reconfiguration. Unfortunately the changed token also triggers this reload which results in hourly reloads.

This leads to a short time, when entities are no available every hour. I'm working on a fix for that right now.

Additionally I made the diagnostic sensors available even if the device is temporarily not connected to myUplink with #140.

You could check, if these sensors (e.g. connection status) show the same "unavailable2 as the other sensors. This would mean, that the API requests did not work at all. (I notices some outages of the API in the lasts weeks.)

**Comment by elden1337** [comment]
I know of a large outage at least for Nibe clients during the night and morning of 13th (last Friday). so perhaps some instabilities have been added on top there.

**Comment by elden1337** [comment]
No fallouts since latest update yesterday @jaroschek 
Closing this.
