### ISSUE TITLE
Supply air entity missing

### ISSUE THREAD

**Issue by Nikojoel** [jaroschek/home-assistant-myuplink#98]
Not sure if this is issue or not, but shooting my shot here anyway.

Just migrated from Nibe Uplink to myUplink and noticed that there is several entities missing from the myUplink integration, most important one being the supply air. Is this due to the fact that even the offical myUplink service is missing those or related to the integration?

**Comment by jaroschek** [comment]
Have you checked the API like described in the README?
https://github.com/jaroschek/home-assistant-myuplink?tab=readme-ov-file#debugging-misbehaving-entities

This integration does only provide entities for parameter points available in the public API. And unfortunately the manufacturers support of the public API is not very consistent.

It is known that the myUplink dashboard has much more to offer than the public API does. This is also already discussed in #48 as the dashboard is using an other API that could be used.

**Comment by Nikojoel** [comment]
I understand. I think the dashboard doesn't even show the entity I'm interested in, might have to connect to the manufacturer in this case. Thank you for the reply!

**Comment by Nikojoel** [comment]
👍
